import type { Metadata } from 'next'
import { abrilFatface, openSans } from '@ui/fonts'
import '@/app/ui/global.css'
import Header from '@ui/header/header'
import Footer from '@ui/footer/footer'


export const metadata: Metadata = {
  title: 'Find Stock',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${abrilFatface.className} ${openSans.className} antialiased `}>
      <body className='bg-chartImage bg-cover bg-center bg-opacity-95 h-full'>
        <div className='min-h-full'>
          <Header />
          {/* make header and place here */}
          {children}
          {/* make footer and place here */}
          {/* <Footer /> */}

        </div>
      </body>
    </html>
  )
}
