import type { Metadata } from "next"

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
interface MetaGenerator {
  title: string,
  description: string
};
export function metaGenerator(data: MetaGenerator): Metadata {
  return {
    title: data.title,
    description: data.description
  }
}
